platform :ios, '8.0'

target 'ChannelChatDemo' do
    pod 'MJRefresh' ,'~> 3.1.0'
    pod 'DZNEmptyDataSet' ,'~> 1.8.1'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'CYLTabBarController'
    pod 'RTRootNavigationController'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SDWebImage'
    pod 'MJExtension'
    pod 'Masonry'
end
